name: Build & Deploy To Production
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci                       # Clean install
    - run: npm run build --if-present   # Build with Polymer, see package.json
    #- run: npm test                    # Disabled, because I haven't created tests yet.

    - name: SFTP Deploy AMS 1 - Clear
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AMS3_SJAARSCHER_01_IP }}
        username: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_USERNAME }}
        key: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_PRIVATE_KEY }}
        port: 22
        script: rm -r /var/www/html/* || true

    - name: SFTP Deploy AMS 1 - Upload
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_USERNAME }}
        server: ${{ secrets.AMS3_SJAARSCHER_01_IP }}
        port: 22
        ssh_private_key: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_PRIVATE_KEY }} # copy private_key from *.pem file, keep format
        local_path: ./build/default/* # copies all files from this folder, default is ./*
        remote_path: /var/www/html/   # copies to this remote_path, default is /
        # sftp args                   # arguments for sftp, optional

    - name: SFTP Deploy AMS 2 - Clear
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AMS3_SJAARSCHER_02_IP }}
        username: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_USERNAME }}
        key: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_PRIVATE_KEY }}
        port: 22
        script: rm -r /var/www/html/* || true

    - name: SFTP Deploy AMS 2 - Upload
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_USERNAME }}
        server: ${{ secrets.AMS3_SJAARSCHER_02_IP }}
        port: 22
        ssh_private_key: ${{ secrets.SJAARSCHER_FRONTEND_DEPLOY_PRIVATE_KEY }} # copy private_key from *.pem file, keep format
        local_path: ./build/default/* # copies all files from this folder, default is ./*
        remote_path: /var/www/html/   # copies to this remote_path, default is /
        # sftp args                   # arguments for sftp, optional
